/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreCadastruRouteImport } from './routes/despre-cadastru'
import { Route as DespreNoiRouteImport } from './routes/despre-noi'
import { Route as PoliticaDeConfidentialitateRouteImport } from './routes/politica-de-confidentialitate'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as ServiciiRouteImport } from './routes/servicii'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreCadastruRoute = DespreCadastruRouteImport.update({
  id: '/despre-cadastru',
  path: '/despre-cadastru',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreNoiRoute = DespreNoiRouteImport.update({
  id: '/despre-noi',
  path: '/despre-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeConfidentialitateRoute =
  PoliticaDeConfidentialitateRouteImport.update({
    id: '/politica-de-confidentialitate',
    path: '/politica-de-confidentialitate',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiRoute = ServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-cadastru': typeof DespreCadastruRoute
  '/despre-noi': typeof DespreNoiRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/servicii': typeof ServiciiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-cadastru': typeof DespreCadastruRoute
  '/despre-noi': typeof DespreNoiRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/servicii': typeof ServiciiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-cadastru': typeof DespreCadastruRoute
  '/despre-noi': typeof DespreNoiRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/servicii': typeof ServiciiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/despre-cadastru'
    | '/despre-noi'
    | '/politica-de-confidentialitate'
    | '/politica-de-cookies'
    | '/servicii'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/despre-cadastru'
    | '/despre-noi'
    | '/politica-de-confidentialitate'
    | '/politica-de-cookies'
    | '/servicii'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/despre-cadastru'
    | '/despre-noi'
    | '/politica-de-confidentialitate'
    | '/politica-de-cookies'
    | '/servicii'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DespreCadastruRoute: typeof DespreCadastruRoute
  DespreNoiRoute: typeof DespreNoiRoute
  PoliticaDeConfidentialitateRoute: typeof PoliticaDeConfidentialitateRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  ServiciiRoute: typeof ServiciiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-cadastru': {
      id: '/despre-cadastru'
      path: '/despre-cadastru'
      fullPath: '/despre-cadastru'
      preLoaderRoute: typeof DespreCadastruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi': {
      id: '/despre-noi'
      path: '/despre-noi'
      fullPath: '/despre-noi'
      preLoaderRoute: typeof DespreNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-confidentialitate': {
      id: '/politica-de-confidentialitate'
      path: '/politica-de-confidentialitate'
      fullPath: '/politica-de-confidentialitate'
      preLoaderRoute: typeof PoliticaDeConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii': {
      id: '/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof ServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DespreCadastruRoute: DespreCadastruRoute,
  DespreNoiRoute: DespreNoiRoute,
  PoliticaDeConfidentialitateRoute: PoliticaDeConfidentialitateRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  ServiciiRoute: ServiciiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
